### ISSUE TITLE
Perl 5.14 requirement

### ISSUE THREAD

**Issue by genio** [pplu/ARGV-Struct#1]
I'm not sure which route you'll choose to take, but ARGV::Struct can't install on anything prior to 5.14 (it seems) due to the way you're declaring the package scope.

```perl
package Foo {
}
1;
```

vs.

```perl
{
    package Foo;
}
1;
```

In attempting to install Paws, this module prevents the installation.  Could you either declare the required version of Perl in your Makefile or alter the package scope so that it will install on prior versions?

Thanks!

**Comment by pplu** [comment]
Hi!

I'm not dedicating too much effort in supporting "old" perls. Are you interested in running Paws on Perls under perls prior to 5.14? If so, I accept patches, but can't promise I'll always keep compatibility with them in new code. This is basically the policy for Paws: https://github.com/pplu/aws-sdk-perl#perl-versions (which I tend to follow in any code I write, but I thought to make it explicit in Paws).

**Comment by pplu** [comment]
Hi!

I've uploaded version 0.03 that is compatible with perls prior to 5.14, so you can install Paws on pre-5.14 installations
